services:
  product-service:
      container_name: product
#      image: amigoscode/product-service:jibMaven
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jfs
        SPRING_DATASOURCE_USERNAME: amigoscode
        SPRING_DATASOURCE_PASSWORD: password
      ports:
        - "8090:8080"
      networks:
        - amigos
  db:
    container_name: jfs-postgres
    image: postgres
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jfs
    ports:
      - "5333:5432"
    restart: unless-stopped
    volumes:
      - db:/data/postgres
    networks:
      - amigos

networks:
  amigos:
    driver: bridge

volumes:
  db:
