services:
  db-local-postgres:
    container_name: jfs-postgres-local
    image: postgres
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jfs
    ports:
      - "5333:5432"
    restart: unless-stopped
    volumes:
      - db-local:/data/postgres
    networks:
      - amigos

networks:
  amigos:
    driver: bridge

volumes:
  db-local: